version: "3.9"
services:
  todo-list-frontend:
    build: ./todo-list-frontend
    links:
      - todo-list-service
    ports:
      - "80:80"
  todo-list-service:
    build: ./todo-list-service
    ports:
    - "8080:8080"
    - "9990:9990"
  todo-list-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todo-list-db
    ports:
    - "3306:3306"