version: "3.9"
services:
  todo-list-frontend:
    build: ../todo-list-frontend
    links:
      - todo-list-service
      - keycloak
    ports:
      - "80:80"
  todo-list-service:
    build:
      context: ../todo-list-service
      args:
        - MYSQL_VERSION
        - TODO_LIST_DB_USER
        - TODO_LIST_DB_PASSWORD
        - TODO_LIST_DB_NAME
        - KEYCLOAK_VERSION
    links:
      - todo-list-db
      - keycloak
    ports:
    - "8080:8080"
    - "9990:9990"
  todo-list-db:
    image: "mysql:${MYSQL_VERSION}"
    environment:
      - MYSQL_ROOT_PASSWORD=${TODO_LIST_DB_ROOT_PASSWORD}
      - MYSQL_USER=${TODO_LIST_DB_USER}
      - MYSQL_PASSWORD=${TODO_LIST_DB_PASSWORD}
      - MYSQL_DATABASE=${TODO_LIST_DB_NAME}
    ports:
    - "3306:3306"
  keycloak:
    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
    - "9080:8080"